-- MySQL Script generated by MySQL Workbench
-- Fri Jan 13 08:50:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shifumi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shifumi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shifumi` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ;
USE `shifumi` ;

-- -----------------------------------------------------
-- Table `shifumi`.`utilisateurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shifumi`.`utilisateurs` ;

CREATE TABLE IF NOT EXISTS `shifumi`.`utilisateurs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `date_de_creation` DATETIME NOT NULL,
  `score_utilisateur` INT(7) NOT NULL,
  `score_hal` INT(7) NOT NULL,
  `nombre_parties` INT(7) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
